fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files  # Ignored for git-lfs files
      args: [--maxkb=100000]  # 100MB
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-json
    - id: check-yaml
    - id: debug-statements
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: double-quote-string-fixer
-   repo: https://github.com/flakehell/flakehell
    rev: v.0.8.0
    hooks:
    -   id: flakehell
        additional_dependencies:
            - flake8-isort==4.0.0
            - flake8-pytest==1.3
            - mccabe==0.6.1
            - pep8-naming==0.11.1
            - pycodestyle==2.7.0
            - pyflakes==2.3.1
            - pylint==2.8.2
            - mypy_extensions
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.3
    hooks:
    -   id: gitlab-ci-linter
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.18.3
    hooks:
    -   id: pyupgrade
